### ISSUE TITLE
Default Protocol issue

### ISSUE THREAD

**Issue by Hexatonix72** [da2x/EdgeDeflector#103]
I was having an issue where no matter what I did I could not get the app to work. However, I found a solution that I didn't see anywhere and wasn't sure how to post it so hopefully the author sees this and adds it to his FAQ. After installing go to Settings>Default apps>Choose default apps by protocol. Then, scroll down to where it says: "MICROSOFT-EDGE URL:microsoft-edge", and select EdgeDeflector as the default app. I hope this helps someone because I've tried and given up on using this app 6 or 7 times and I got bored and thankfully found this fix.
-Hex

**Comment by da2x** [comment]
The above solution referenced from the page that automatically opens after installing EdgeDeflector:
https://github.com/da2x/EdgeDeflector/wiki/Thank-you-for-installing-EdgeDeflector

Have you got any feedback on that page? You should have seen it six–seven times after installing without noticing it, so there’s obviously room to improve that page.

The underlying issue is that the installer can’t *reliably* change this protocol. The installer instructs Windows to open a dialog that asks you to chose to open `microsoft-edge:` links in EdgeDeflector or Edge. Windows doesn’t always open this dialog and just forces it to open in Edge. It works for some users, and not for others. (It also reverts back to Edge for some users after installing major feature updates to Windows.)

**Comment by da2x** [comment]
Hi, would you be interested in helping me test an updated installer?
1. Uninstall EdgeDeflector from Add and Remove Programs.
2. Press Cmd+R, type `microsoft-edge:https://example.com`, and press Enter. (It should open in Edge.)
2. Download and install [this test version](https://github.com/da2x/EdgeDeflector/files/6291296/EdgeDeflector_install.exe.zip).

Is this better?
