### ISSUE TITLE
Install the app per machine

### ISSUE THREAD

**Issue by xmha97** [da2x/EdgeDeflector#112]
Hi,
I want to install the app for all users to %ProgramFiles% instead of %LocalAppData%
Like other apps:
![image](https://user-images.githubusercontent.com/23485114/120572351-074f2100-c431-11eb-87ca-74b7afe4e381.png)
you should update installer.

**Comment by da2x** [comment]
The installer was changed to install per-user because anti-virus vendors really hated the old installer. Per-user installs has several advantages including not requiring admin privileges to install it. In any case, the app must be manually configured per-user due to changes in Windows 10. This is more esily achieved with the help of the installer.
