### ISSUE TITLE
EdgeDeflector not listed as option for microsoft-edge protocol

### ISSUE THREAD

**Issue by nullnetworks** [da2x/EdgeDeflector#114]
In the 'Choose default apps by protocol' I have 5 options for MICROSOFT-EDGE:
Microsoft Edge(with edge logo)
My Username(no logo)
Microsoft Edge(no logo)
Microsoft Edge Beta(with edge logo with 'BETA' on it)
Look for an app in the Microsoft Store(with windows store logo)

I've tried re-running the installer and re-starting the machine, neither has had any effect.
Any idea how I can resolve this?

**Comment by da2x** [comment]
Please go to Windows Settings: Apps: Default apps and click Reset to defaults. Reboot. Does that fix it?

**Comment by JVT038** [comment]
I have the same issue (version 1.2.2.0), and I checked my registry and I saw that `SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\EdgeDeflector` doesn't exist. It's literally not in my registry.
Maybe something's wrong with my installer? I used the latest release

**Comment by da2x** [comment]
> Please go to Windows Settings: Apps: Default apps and click Reset to defaults. Reboot. Go back into Windows Settings: Apps: Default Apps: By protocol: MICROSOFT-EDGE. Does that fix it?

@JVT038 does this work for you?

@JVT038 Just to verify, that should be (`HKCU` prefix) `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\EdgeDeflector.exe` (`.exe` suffix.) Have it ended up somewhere else? Please search for `EdgeDeflector` in your registry and let me know what you find (you can ignore any with `{random-id}` in the path.)

**Comment by nullnetworks** [comment]
I tried resetting to defaults then rebooting, no change.
I tried uninstalling edgedeflector which weirdly opened the 'open with' dialog instead of the uninstaller, so I went to the folder where it was installed and ran the uninstaller from there, rebooted, reinstalled, no change.

I didn't change the install directory from the installer.
I didn't have any earlier versions installed.
I've checked the registry using regedit and all of the keys listed are there.

Setting up a new user account and re-installing edgedeflector once logged in worked for the new account. I just don't know how to make that success translate into it working on my main account.

Thanks for your patience and help.

**Comment by JVT038** [comment]
> 
> 
> > Please go to Windows Settings: Apps: Default apps and click Reset to defaults. Reboot. Go back into Windows Settings: Apps: Default Apps: By protocol: MICROSOFT-EDGE. Does that fix it?
> 
> @JVT038 does this work for you?
> 
> @JVT038 Just to verify, that should be (`HKCU` prefix) `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\EdgeDeflector.exe` (`.exe` suffix.) Have it ended up somewhere else? Please search for `EdgeDeflector` in your registry and let me know what you find (you can ignore any with `{random-id}` in the path.)

It unfortunately doesn't. 
But I have searched through the registry, and I found EdgeDeflector.exe on `\SOFTWARE\Classes\Applications\EdgeDeflector.exe`

**Comment by da2x** [comment]
This should be fixed in [version 1.2.3.0](https://github.com/da2x/EdgeDeflector/releases/tag/v1.2.3.0).

**Comment by saifster9** [comment]
Unable to redirect cortana searches after a recent reinstall of the program. I believe windows has modified the location where non-standard apps are located.... looked up in the registry and EdgeDeflector doesn't exist in the aforementioned path.
This is because other non-windows approved apps also started to crash at the same time...
did a quick dig around github/reddit and couldn't find any info about it...

Expected Registry Entry:
HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\EdgeDeflector.exe

Current Location:
HKCU\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Compatibility Assistant\Store

Is this something which can be fixed on my machine?

Currently when I install EdgeDeflector, it shows up in the control panel list, but no longer in the Default Apps page. Instead there is a blank icon with Edge written on it.
Here is a screenshot:

![EdgeDeflector](https://user-images.githubusercontent.com/57546737/147443293-bd35573d-04f0-443d-9c6c-dfe869825592.png)

Any assistance is greatly appreciated.

**Comment by da2x** [comment]
See issue #141.
