### ISSUE TITLE
Does EdgeDeflector_install.exe have embedded viruses or payload?

### ISSUE THREAD

**Issue by Mac404** [da2x/EdgeDeflector#116]
Hi

I just downloaded the latest EdgeDeflector_install.exe and ran it against Virustotal.com and it found the 3 following payloads:

3 security vendors flagged this file as malicious
Checksum: 3b1cb1e9a8187e16f6447b81785632fa5989d72a0475d82390ba52448a5defa5
EdgeDeflector_install.exe

SecureAge APEX : Malicious

BitDefenderTheta : Gen:NN.ZemsilF.34738.xm0@auq8Teh

McAfee-GW-Edition : BehavesLike.Win32.Downloader.qc

Should I worry?

**Comment by da2x** [comment]
Some anti-virus vendors assumes anything unfamiliar is untrustworthy. Stranger-danger!

There is absolutely nothing I can do about it. The trust level tends to change over time as the anti-virus vendors has seen the same program on many cuatomer systems. You can wait a month and try again. You can reach out to the vendors that flag it as malicious and ask for a manual review.

The code is open source. You can read through [Program.cs](https://github.com/da2x/EdgeDeflector/blob/c725a1e03ab1e48496a8dff24a36c64d6a3f5d5d/EdgeDeflector/Program.cs) in half a minute. You may not fully understand the code, but it's fairly readable and you can guess what it does. You'll also see that it doesn't do anything malicious like delete or encrypt your files or steal all your data.

**Comment by DataCZ** [comment]
@da2x the false positive should probably be reported by you I think.
https://www.secureage.com/article-report-false-positive
https://www.mcafee.com/enterprise/en-us/threat-center/detection-dispute-form.html?region=us
https://www.bitdefender.com/consumer/support/answer/40673/

**Comment by Mac404** [comment]
Thanks Daniel for your reply. It's good to know that it's a false positive. Thanks.

    On Friday, June 11, 2021, 6:17:07 PM PDT, Daniel Aleksandersen ***@***.***> wrote:  
 
 


Some anti-virus vendors assumes anything unfamiliar is untrustworthy. Stranger-danger!

There is absolutely nothing I can do about it. The trust level tends to change over time as the anti-virus vendors has seen the same program on many cuatomer systems. You can wait a month and try again. You can reach out to the vendors that flag it as malicious and ask for a manual review.

The code is open source. You can read through Program.cs in half a minute. You may not fully understand the code, but it's fairly readable and you can guess what it does. You'll also see that it doesn't do anything malicious like delete or encrypt your files or steal all your data.

**Comment by Mac404** [comment]
I will report them to the vendors. Thanks

    On Saturday, June 12, 2021, 3:18:15 AM PDT, DataCZ ***@***.***> wrote:  
 
 


@da2x the false positive should probably be reported by you I think.
https://www.secureage.com/article-report-false-positive
https://www.mcafee.com/enterprise/en-us/threat-center/detection-dispute-form.html?region=us
https://www.bitdefender.com/consumer/support/answer/40673/

**Comment by KC20cy** [comment]
Hi there, I read this thread twice and noticed about the part False Positive, I am not a coder, so I would like to be sure before I install the app, base on all recent discussion, the app is safe, am I correct?

**Comment by da2x** [comment]
Some anti-virus vendors assume all unknown programs are “unsafe.” I can’t do anything about that. After a few weeks or months, anti-virus vendors will revert their decision and say the program is “safe.” Because nothing bad that can be attributed to the program in question has been observed in meantime. You can wait and hope all vendors change will change security evaluation to say it’s secure if that makes you sleep better at night.

You can never be 100% safe. I’m the lead developer and I say the installer is — to the best of my ability — safe. Microsoft (who owns GitHub) can, of course, have replaced the installer I uploaded with NSA spyware. Or maybe some unknown program on my computer added a viral payload while I compiled the program. Who knows? You can never know for sure. Modern computing is based on trust. Do you trust GitHub to not interfere with app distribution? Do you trust me to make a reasonably secure program without viruses?

You can either download the source code, evaluate it, review it for security blunders, and build it locally on your computer; or you can trust me and the toolchain I used to build and distribute the program.

I can’t guarantee 100% that my Windows computer hasn’t been compromised by malicious hackers in black hoodies with code flying in the air around them. Can you for your own computer? I’ve done my best to ensure that hasn’t happened. I always review the compiled binary program and verify that nothing obvious has snuck in. But I would probably not detect something super stealthy making that made a subtle change.

That’s why I upload it to VirusTotal before uploading it to GitHub (which is how VirusTotal and its partner anti-virus vendors knew about it before I released it.) Some vendors gave it generic stranger-danger review, but none of the vendors detected any signatures or behaviors of any known malware.

**Comment by KC20cy** [comment]
Hey, thanks for your reply, I will take it into my consideration.
