### ISSUE TITLE
will not install

### ISSUE THREAD

**Issue by BradTucker** [da2x/EdgeDeflector#121]
I have down loaded EdgeDeflector but when I try to install it, I am taken to a web window asking if I want Edge as my default browser. I tried accepting Edge as my default browser and reinstalling EdgeDeflector, but I am taken to the same browser window. When I check to see the details, it tells me the program is incomplete, and that it is not compatible. I ran the compatibility program but that didn't work. Running it as an administrator didn't help either.
![EdgeDeflector 002](https://user-images.githubusercontent.com/86531198/123522862-0f3b6300-d675-11eb-8015-b2a38e842706.jpg)
![EdgeDeflector 003](https://user-images.githubusercontent.com/86531198/123522864-16627100-d675-11eb-9e73-917363a68629.jpg)

**Comment by da2x** [comment]
[The page](https://www.daniel.priv.no/tools/edgedeflector/post-install.html) that opens at the conclusion of the installation contains some manual set-up steps. (The remaining steps can’t be automated because of Windows policies.) The page is blocked on your network. I can’t do anything about that, however. Please adjust your network settings to allow the page to open. Please share details on what blocked it, though. I’m curios about what’s blocking my site. Alternatively, you can open the page from your phone or another device.

The compatibility troubleshooter just checks if the program exit quickly and sees that as a problem. EdgeDeflector just runs for a few milliseconds by design, so it trips up the troubleshooter. It should work just fine after completing the manual setup steps.

**Comment by ryank425** [comment]
Here is archive link for those of you who can't access that page.

https://web.archive.org/web/20210611130654/https://www.daniel.priv.no/tools/edgedeflector/post-install.html
