### ISSUE TITLE
Does edge deflector auto update itself?or i should manually update it everytime?

### ISSUE THREAD

**Issue by yazan1107** [da2x/EdgeDeflector#144]
Does edge deflector auto update itself?or i should manually update it everytime?

**Comment by da2x** [comment]
It doesn’t auto-update. It took four years between versions 1.1.3.0 and 1.2.0.0. The only times it has really needed updates are when Microsoft actively sabotages it. (Twice in the project’s lifetime so far.) I’ve not wanted to introduce auto-updates because it would open a possible security whole and make antivirus scanners more suspicious of the app. It shouldn’t have been necessary with more updates if Microsoft had just had the fear of antitrust regulators in them.
