### ISSUE TITLE
Version 1.1.1.0 Is being flagged as a trojan by windows defender

### ISSUE THREAD

**Issue by jrkd** [da2x/EdgeDeflector#18]

**Comment by da2x** [comment]
Thank you for reporting this.

As far as I can tell, neither the current program nor the installer is being flagged as malicious by Microsoft’s engine according to VirusTotal ([installer](https://www.virustotal.com/en/file/2c12a85769c68468721a9a096dde95a065dedac5266bef22a65fe5721369fc11/analysis/1501761837/), [program](https://www.virustotal.com/en/file/03a400b88c2918c6834d86b50389e1b1f226d094541649784bf3bd53679a8c83/analysis/1501762063/)). Independent testing with SmartScreen and Windows Defender also doesn’t bring up any false positives.

Four other providers flag it as suspicious because it’s an unsigned executable. I’m doing this for free, so I’m not going to cover the high ongoing cost of obtaining and maintaining a code signing certificate for this project.

The code is open-source. Anyone who is suspicious about EdgeDeflector may inspect he code and build their own copy from source.

**Comment by jrkd** [comment]
Hey, 

Thanks for the reply. I mentioned it cause chrome blocks the download. Interestingly 1.0.1 passes the virus checks fine. 

I dont have any 3rd party anti virus, this is literally just up to date windows defender. The unsigned exe stuff is fine, comes with the territory, but windows def. isn't worried about that. 

Not saying the code is shifty, it just stops some people downloading it.

**Comment by Nizars** [comment]
Hi, I don't think this should be a closed issue. There is no way that I will run a program with those kinds of warnings. It should be looked into even if it was false positive.

![2017-08-04 21_08_27-settings](https://user-images.githubusercontent.com/16970186/28983306-75fc0f04-7959-11e7-8502-b3ae0d77cb14.png)

![2017-08-04 21_09_07-antivirus scan for 2c12a85769c68468721a9a096dde95a065dedac5266bef22a65fe5721369f](https://user-images.githubusercontent.com/16970186/28983310-7b23b25c-7959-11e7-9d71-3114ab4d3ba6.png)

![2017-08-04 21_09_21-antivirus scan for 03a400b88c2918c6834d86b50389e1b1f226d094541649784bf3bd53679a8](https://user-images.githubusercontent.com/16970186/28983318-8124d5dc-7959-11e7-9b78-283464f382d2.png)

**Comment by da2x** [comment]
I can’t do anything about this. You’ve allowed Microsoft to control what you can and cannot download.

You guys can report a false positive to Microsoft, however!

1. Open Microsoft Edge.
2. Download EdgeDeflector, wait until you’re told you can’t run it.
3. Click View downloads
4. Right-click on the blocked EdgeDeflector_install.exe and choose `Report that this download is safe.`
5. Fill out the online report form

You can also choose Run anyway from the same context menu to bypass Microsoft SmartScreen, if you’re comfortable with bypassing it.
