### ISSUE TITLE
Prompting to Close Firefox when its already running

### ISSUE THREAD

**Issue by Starstrike** [da2x/EdgeDeflector#41]
Seems there is an issue with Firefox (at least 57) where doing a search through Cortana will make Firefox prompt to close and reopen with a new process which then will show the search query. Didnt see this as an issue already and not sure if anyone else noticed it but I cant get the app to work in Firefox if its already running. Works fine when its closed.

**Comment by Starstrike** [comment]
Just to add...this appears to only be an issue if Firefox is launched using the -profile command-line. Once I removed the command-line options and ran Firefox using the default profile, searching through Cortana worked fine.

**Comment by da2x** [comment]
I doubt this has anything to do with EdgeDeflector.

Please try to reproduce this, but instead of using EdgeDeflector just press Win+R, type `https://example.com/`, and press Enter. If the problem persists with this method, then the issue is most likely with Firefox. (Please do report it in their bugzilla database!)

**Comment by spikespaz** [comment]
I can confirm that this is not Mozilla's bug. It is a problem with Edge Deflector.

I have the same issue.

**Comment by spikespaz** [comment]
@Starstrike My [alternative](https://github.com/spikespaz/search-deflector) should fix this issue.

Please don't get offended if you think I'm competing, we do different things, I redirect searches and the browser, you just redirect the browser.
