### ISSUE TITLE
Can’t hijack links when “Optimize taskbar web search results for screen readers” option is enabled

### ISSUE THREAD

**Issue by matuyo2002** [da2x/EdgeDeflector#46]
i have done everthing from installing and reinstalling to rebooting my computer changing preferences and stuff.
teh problem is that everything shows up how it should, but when i search in cortana nothing happens it just loads and thats it

**Comment by da2x** [comment]
What version are you using? Have you upgraded to [1.1.3](https://github.com/da2x/EdgeDeflector/releases/latest)?

**Comment by matuyo2002** [comment]
Well i downloaded the latest version that appeared on the page :/

**Comment by tonaz** [comment]
Doesn't work for me neither, followed all steps, i also can see EdgeDeflector in the protocol association and everything... But Cortana opens Edge or Internet Explorer anyways.
I think latest Win update completely protected the Cortana-Edge thing.

**Comment by da2x** [comment]
What is your exact Windows version and build? (Press Win+R, type `winver`, and press Enter.)

**Comment by tonaz** [comment]
10 home x64 - 1709 build 16299.125

**Comment by da2x** [comment]
That version works just fine with the latest version of EdgeDeflector. I just tested with that version.

Is Microsoft Edge your default web browser? If not then you may have a corrupt file and protocol association registry (unfortunately, this happens all the time Windows Vista and later). You can reset it by going to Windows Settings: Apps and Features: Default apps and clicking the Reset button. You should log out and in again, and then try changing your default web browser and either resetting EdgeDeflector as the protocol handler for microsoft-edge (or reinstalling EdgeDeflector).

Oh, and press Windows key + F to open the Windows Feedback Hub and complain to Microsoft about the need to install EdgeDeflector in the first place.

**Comment by tonaz** [comment]
I reset default apps.
Logged out.
Logged it.
Set Chrome as default browser.
Reinstalled EdgeDeflector, double clicked it.
Put EdgeDeflector as Edge protocol.

No luck.

**Comment by tonaz** [comment]
I tried removing IE11 from "features and apps" menu.
If i say hey Cortana search hello, nothing happens now :-\  
I set everything at default, even Edge as browser.
Talking to cortana it do not open NOTHING ...
This is getting puzzling...

**Comment by tonaz** [comment]
Ok this is crazy: i went to Microsoft Edge settings > view advanced settings > optimize taskbar web search results for screen readers and i switched it off.
It works...
Unbelieavable Micro$oft.

**Comment by da2x** [comment]
> Microsoft Edge settings > view advanced settings > optimize taskbar web search results for screen readers and i switched it off.

Was this setting enabled by default? Do you use any accessibility tools, program, or hardware? Do you use any assistive features of Windows that you’re aware of?

**Comment by hennessyp** [comment]
I've tried everything listed above and no luck.

I reset default apps.
Logged out.
Logged it.
Set Chrome as default browser.
Reinstalled EdgeDeflector.
Put EdgeDeflector as Edge protocol.
Switched 'optimize taskbar web search results for screen readers' off in Edge settings.

Still nothing happens when I search using Cortana, just a loading wheel.

**Comment by bouwput** [comment]
I also can't get it to work unfortunatly, the idea is great though.
It only loads for a second and does nothing.
the win + R command works fine

Switched 'optimize taskbar web search results for screen readers' off in Edge settings.
Chrome as default browser.
Windows 10 Pro - Version 1709(OS Build 16299.192)


my event log shows the following errors:
ERROR: Source:.NET runtime

> Application: EdgeDeflector.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.UriFormatException
   at System.Uri.CreateThis(System.String, Boolean, System.UriKind)
   at EdgeDeflector.Program.OpenUri(System.String)
   at EdgeDeflector.Program.Main(System.String[])

ERROR: Source: Application error

> Faulting application name: EdgeDeflector.exe, version: 1.0.1.0, time stamp: 0x58a26e86
Faulting module name: KERNELBASE.dll, version: 10.0.16299.15, time stamp: 0x4736733c
Exception code: 0xe0434352
Fault offset: 0x0000000000013fb8
Faulting process id: 0x2234
Faulting application start time: 0x01d39b6d51bae95a
Faulting application path: C:\Program Files (x86)\EdgeDeflector\EdgeDeflector.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 888b340e-2016-446c-89a3-1833723c2bd4
Faulting package full name: 
Faulting package-relative application ID: 

Information: Windows Error report:

> Fault bucket 129567754791, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0
Problem signature:
P1: EdgeDeflector.exe
P2: 1.0.1.0
P3: 58a26e86
P4: System
P5: 4.7.2556.0
P6: 59b83638
P7: 36f
P8: 73
P9: System.UriFormatException
P10: 

I hope this helps

**Comment by da2x** [comment]
@bouwput, even with “optimize taskbar web search results for screen readers” enabled?

**Comment by bouwput** [comment]
It opens in IE11 when I enable that setting

**Comment by da2x** [comment]
The option has been removed from Windows.
