### ISSUE TITLE
Taskbar search stays empty after reboot

### ISSUE THREAD

**Issue by twity1337** [da2x/EdgeDeflector#79]
I installed EdgeDeflector two days ago. 
Everything worked fine, links had been opened in Chrome (the default browser) where Chrometana forced the Bing search to redirect to Google.

But now I discovered an issue after rebooting the system. The search in the **Start Menu stays empty**.
It does not load anything **nor shows entries for apps, that I have installed**. Only the search input field, and an scroll bar on the right side.

After uninstalling EdgeDeflector (and removing all the orphaned registry entries, which the uninstaller did not remove automatically #80) and rebooting the system, everything works fine again. Of course, the links are opening in Edge as before.

So it must be caused by EdgeDeflector.
Probably Microsoft patched the ability to exchange the ProtocolHandler for Microsoft-Edge URLs..

**My Windows Version:**
Version 10.0.18363.592 - Update 1909

**Comment by freeshrugsxd** [comment]
Not entirely sure this is _caused_ by EdgeDeflector directly. Many people (including me) had the same problem over the last 24 hours. See [this post](https://www.reddit.com/r/Windows10/comments/ez8gan/windows_10_search_bar_not_working_after/) on the windows 10 subreddit. It should be fixed by now. At least I don't have any issues anymore.

**Comment by da2x** [comment]
EdgeDeflector only registers a protocol handler. It doesn’t actually change the start menu or any other  Windows component.

**Comment by da2x** [comment]
https://www.theregister.co.uk/2020/02/05/windows_10_binged/
