### ISSUE TITLE
EdgeDeflector just breaks links from the search bar rather than redirecting them

### ISSUE THREAD

**Issue by SirDragonClaw** [da2x/EdgeDeflector#81]
On the latest public build of Windows 10 if I search for a website from the start search field (something I do 20-30 times daily) I normally get that search opened up in Edge.

After installing EdgeDeflector and setting it to be used for Edge protocalls it just blocks the page from launching in any browser, as soon as I swap protocalls back to edge then it launches in edge.

Running microsoft-edge://example.com/ from run does correctly get deflected from edge to Firefox, however, it is only when links are opened from the search bar next to the start icon that the issue occurs.

**Comment by da2x** [comment]
Hi, thanks for reporting! I’m gonna need to ask for three pieces of information from you:

Please confirm that [this  bugged option is disabled](https://github.com/da2x/EdgeDeflector/issues/46).

Please run the [special debug build as instructed here](https://github.com/da2x/EdgeDeflector/issues/52#issuecomment-368151247). Install the build, then reproduce the problem. You should get a window opening (in some browser or another) with a new page. Copy the full URL of that page here. It’ll encode a copy of the original link you tried to open for debugging purposes.

Please provide your complete Windows build info. Press Win-key + R, type `winver` (“Windows version”) in the dialog, and press Enter to find it.

**Comment by jamesdeluk** [comment]
I'm having the same issue.

My Edge doesn't have that option.

When I try the debug build, nothing happens. It doesn't install, and it doesn't run (i.e. it's not in Task Manager).

1909 18363.778

**Comment by da2x** [comment]
> When I try the debug build, nothing happens. It doesn't install, and it doesn't run (i.e. it's not in Task Manager).

It doen’t run all the time. It launches when you click on a link. Right-click on the debug exe once and select Run as admin. Nothing happens. Then, follow the step you normally do to open a link. It should open a special link in your web browser. Copy this link here.

**Comment by francescoboc** [comment]
I don't have that option in Edge.

**Comment by 2br-2b** [comment]
Does it maybe have something to do with the implementation of the Chromium-based Edge?

**Comment by Jean-Le-Henaff** [comment]
I experienced the same issue and have gone through almost each step of the troubleshooting help.

Disabling the option "Optimize taskbar web search results..." in Edge was not possible since it no longer exists in my current version. To clear things up, Edge has removed this option and not hidden it since the associated registry key no longer exists. So we no longer have control over this.

However, after resetting to defaults, I found out that the microsoft-edge protocol was not associated with EdgeDeflector but with Edge. After changing that it worked fine. I believe that before doing this, it was not associated either. So it seems that the installer does not configure the protocol correctly in some cases at least.

System version : Windows 10 Pro 2004 - 19041.388

**Comment by da2x** [comment]
> So it seems that the installer does not configure the protocol correctly in some cases at least.

The underlying problem is that the file and protocol association database gets corrupted. It’s a long-standing bug in Windows. I can’t really do anything about it. This affects every program.
