### ISSUE TITLE
(Feature request) Add option to specify command line arguments to default browser

### ISSUE THREAD

**Issue by samarthc** [da2x/EdgeDeflector#87]
Let me start by saying I understand that this is not a project that you would wish to take up a lot of your time. If you could let me know how you built the release binaries from the source I will be well on my way to add what I want on my own fork.

I like to keep multiple tabs and windows open in Firefox. If an instance of Firefox is not already running, all my previously-open tabs and windows add significant overhead to launching Firefox for a simple search from Cortana.

I have an idea for a solution: I created a new user profile in Firefox that will be used only for Cortana searches. If there were a way to specify command-line arguments I'd pass "-P <profile-name>". This will open Cortana searches in the separate search profile with no overhead from tabs kept open in my default profile. 

Perhaps an easy fix is adding an optional field in the installer that allows one to specify command-line arguments, that are then written to the registry (is that good practice for making a string available to the program as something like a global variable?)

**Comment by da2x** [comment]
The underlying issue seems to be that you have too many tabs. Open about:config and search for lazy. Look for something called lazy-something-something-background-tabs. It will stop loading background tabs when you open Firefox until they're selected. Lazy loading of background tabs should solve the problem.

It won't be that easy to fix. All the program does is intercept microsoft-edge: and convert it into https:. It's unaware of browser binaries, their locations, command line arguments, and the like. It just takes in one URL and turns it into another. Windows does the rest.

Open the project in Visual Studio and hit build release. You'll find a binary in the build release directory. There's a Nullsoft installer script used to wrap that binary in an installer.

(Sorry about the vague reply. I'm replying for my phone to answer you quicker but I can't lookup the details as easily as from my laptop. )

**Comment by samarthc** [comment]
It seems my problem stems from all the add-ons I have installed on my default Firefox profile and not the tabs. I do have lazy loading enabled for session restore and launching Firefox in safe mode reduces startup time significantly.

The only solution I have is to create a different profile for quick Cortana searches. I suppose my case is pretty idiosyncratic, so I'll try and tinker on my own fork.

Thanks for pointing me to Visual Studio!

**Comment by da2x** [comment]
> It seems my problem stems from all the add-ons I have installed on my default Firefox profile and not the tabs.

Yikes. Get rid of the worst offenders. `about:performance` or `about:telemetry#keyed-histograms-tab_extension` might help you identify which ones are causing the issue.
