### ISSUE TITLE
EdgeDeflector Does not work on the new version of Microsoft Edge.

### ISSUE THREAD

**Issue by ThalyssonLeite** [da2x/EdgeDeflector#89]
I tried every step of solution. But it just dosen't works. The exemple.com test work. But when i write something in the search bar nothing happens. My cursor load something and then disapears. nothing come. But when I change in the normal menu my favorite browser to Edge and I do the the search in Cortana again it works (but now in the Edge, I hate it).

**Comment by ivan-kljajic** [comment]
Apologies if this doesn't work for you, but...

I was worried about this, but MS offered the upgrade to the new Edgium yesterday, and after installing it EdgeDeflector still works as far as I can tell.

I can enter a URL on the start menu and Firefox will open after a second click*** (which seems to be your issue - see below).

Also, I can click on on the Lock Screen picture "show me more" links, and on Windows Update History KBxxx links and they will all open in Firefox.

My OS is Windows 10 1909 x64. I "install" this app by compiling the exe (no code changes) and directly "registering" it in a directory of my choice by running it without args (I think). But I don't think this changes my experience, Maybe Windows 1909 might (as opposed to 2004).

*** Regarding start menu searches:

I have Cortana web search results turned off on my system, but I can still type in URLs and launch them in Firefox.
I had to re-affirm my choices to (1) Keep using EdgeDeflector to handle the requests, and (2) Keep using Firefox as my default browser. I think this is the same whenever any new app is installed that wants to become a new default for something.

For start menu searches I also need to do the extra step of clicking on the highlighted link after typing it in. But I think this is normal since I turned off web searches in Cortana. The first clip brought up the dialogues asking to re-affirm my previous default actions, and now Firefox just opens.

![Cort](https://user-images.githubusercontent.com/56899869/87542972-32c90000-c6e7-11ea-8f1c-4a327566b14c.png)

**Comment by alexbuzzbee** [comment]
I installed via the NSIS installer. I had to change the protocol association manually in settings, but once I'd done that it seems to work perfectly fine. If someone can point me at a known `microsoft-edge:` URI in Settings or somewhere, I can test there as well, but the Run box, the Search box, and the links I've tested in Settings have all worked.

**Comment by ivan-kljajic** [comment]
I realised after submitting that I didn't fully read the original issue text saying that example.com works for the OP (sorry about that), so for completeness I temporarily re-enabled Cortana web search (I hate it) and logged back in and still Firefox opens as desired after typing in a web search query.

This is even if no web browser is running when I type in the web search: Firefox is launched to show the Bing search results.

And as I suspected, with web search enabled I didn't need to do the extra please make a selection step/click after typing in the search box.

Still the Windows 1909 caveat though.

**Comment by Dinjoralo** [comment]
> I installed via the NSIS installer, and am also running 1909. I had to change the protocol association manually in settings, but once I'd done that it seems to work perfectly fine. If someone can point me at a known `microsoft-edge:` URI in Settings or somewhere, I can test there as well, but the Run box, the Search box, and the links I've tested in Settings have all worked.

I've gotten it to work by going through Windows' "Set defaults by app menu".
![image](https://user-images.githubusercontent.com/2925248/88197560-43f29f00-cc08-11ea-9a6e-5eb11b7c4218.png)
From there, you can go to Edge Deflector in the list of apps and set the URI that Windows uses.

**Comment by ziggythehamster** [comment]
@Dinjoralo's advice worked for me on 20H2. I guess the start menu/Cortana search no longer tries to prompt you to choose a default application

**Comment by RealFantaCoke** [comment]
Yeah, I've had the same error. I set up everything and then I selected "Choose default apps by protocol".

There it wasn't changed before, so I changed "microsoft-edge:" manually to EdgeDeflector.

Maybe an update from the Developer can fix this.

**Comment by da2x** [comment]
> Maybe an update from the Developer can fix this.

It’s not on me — I promise! This problem isn’t unique to EdgeDeflector.

The default browser setting is protected, so I can’t just edit the registry directly to make this change. (To prevent malware and “legitimate” web browsers from certain vendors from hijacking the default web browser setting.) The dialog prompt and user-interaction is the only method available.

This is a bug in how Windows handles protocol and file extension associations. EdgeDeflector prompts you once as part of the installation. Windows handles everything about that prompt dialog. The problem is that Windows just ignores what the user selected. The [third troubleshooting step](https://github.com/da2x/EdgeDeflector/wiki/Troubleshooting) deals with this situation. Often, this is caused by a corrupt protocol association registry. [The forth troubleshooting step](https://github.com/da2x/EdgeDeflector/wiki/Troubleshooting) deals with this situation.

**Comment by reloxx13** [comment]
@Dinjoralo method did work for me on win10x64 2004
i had to choose edgedeflector and now everything i search is openign in firefox with google.
thank you!

"open edgedeflector with edgedeflector"
![grafik](https://user-images.githubusercontent.com/14855001/97781299-a1dd3e00-1b8a-11eb-8156-189cb94974c0.png)

**Comment by Justin-Maxwell** [comment]
@Dinjoralo method fixed it for me too.   
@da2x It would be worth highlighting this method in the instructions since most users are not going to look in GitHub Issues… That said, thank you so much for the tool!

**Comment by da2x** [comment]
> It would be worth highlighting this method in the instructions since most users are not going to look in GitHub Issues

It’s on the troubleshooting page. It’s the third step I linked to above. It has been on that page for almost four years. The page is a top-result in Bing and Google if you try describe the problems to a search engine. The troubleshooting page is also linked from the main project page and on [the page that opens automatically after you install EdgeDefelctor](https://github.com/da2x/EdgeDeflector/wiki/Thank-you-for-installing-EdgeDeflector).

The main problem here is that this will either work out-of-the-box, or it requires some manual intervention in the Settings app. I can’t deliver a “just works” solution when the bug is in how Windows 10 itself handles protocol–app associates. It only affects some users depending on the state of Windows’ file and protocol associations before installing EdgeDeflector, though. EdgeDeflector is being blamed for a problem that is really just a symptom of Windows misbehaving. You may notice the same problem after installing a new video player or email client.

I don’t really know what I can do to help users and communicate all of this better.

**Comment by ivan-kljajic** [comment]
Just fyi.
Updated from 1909 to 20H2 today and didn't need to change anything. Edge reverted itself to version 84 during the update, but even after updating it back to 87 there was no issue: didn't need to make any protocol changes.
Maybe this was because I had already confirmed via a half-expected popup from Windows to keep EdgeDeflector as the protocol handler after installing Edge in July on Windows 1909 and then navigating a url. If I had just escaped the popup everything would probably have reverted to defaults. That's my experience anyway.

**Comment by the-phuctran** [comment]
![image](https://user-images.githubusercontent.com/43033446/121171492-c320ae00-c880-11eb-8ba9-bd46f2547ebe.png)
Today I've just reinstalled it and when I go to setting to set it to default, it's only show my PC username next to the grey icon additionally. I doesn't work when I select those option anymore.

**Comment by da2x** [comment]
@the-phuctran Does it appear after a restart? If not can you click the Reset to defaults button on the settings screen?

If you're comfortable with the System Registry Editor (regedit.exe), you can check these paths:
https://github.com/da2x/EdgeDeflector/blob/69ad543d41eefbe3ed04eee7ca5777fca26a3fa1/EdgeDeflector/resources/nsis_installer.nsi#L51-L75
